#!/bin/bash
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=ajaxtags-1.2-beta3.jar	-DartifactId=ajaxtags-1.2-beta3
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=ant-junit-1.8.4.jar	-DartifactId=ant-junit-1.8.4
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=antlr-2.7.5H3.jar	-DartifactId=antlr-2.7.5H3
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=asm-attrs.jar	-DartifactId=asm-attrs
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=asm.jar	-DartifactId=asm
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=atomfeed-client-1.9.4-SNAPSHOT.jar	-DartifactId=atomfeed-client-1.9.4-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=atomfeed-commons-1.9.4-SNAPSHOT.jar	-DartifactId=atomfeed-commons-1.9.4-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=atomfeed-server-1.9.4-SNAPSHOT.jar	-DartifactId=atomfeed-server-1.9.4-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=bahmni-migrator-5.1-SNAPSHOT.jar	-DartifactId=bahmni-migrator-5.1-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=barbecue-1.0.6b.jar	-DartifactId=barbecue-1.0.6b
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=c3p0-0.9.1.jar	-DartifactId=c3p0-0.9.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=castor-1.0.5-xml.jar	-DartifactId=castor-1.0.5-xml
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=castor-1.0.5.jar	-DartifactId=castor-1.0.5
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=cglib-2.1.3.jar	-DartifactId=cglib-2.1.3
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-beanutils.jar	-DartifactId=commons-beanutils
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-codec-1.3.jar	-DartifactId=commons-codec-1.3
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-collections-2.1.1.jar	-DartifactId=commons-collections-2.1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-digester.jar	-DartifactId=commons-digester
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-fileupload-1.2.1.jar	-DartifactId=commons-fileupload-1.2.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-httpclient-3.1.jar	-DartifactId=commons-httpclient-3.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-io-2.4.jar	-DartifactId=commons-io-2.4
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-javaflow-20060411.jar	-DartifactId=commons-javaflow-20060411
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-lang-2.1.jar	-DartifactId=commons-lang-2.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-lang3-3.1.jar	-DartifactId=commons-lang3-3.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-logging.jar	-DartifactId=commons-logging
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=commons-validator-1.3.1.jar	-DartifactId=commons-validator-1.3.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=crypto.jar	-DartifactId=crypto
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=dom4j-1.6.1.jar	-DartifactId=dom4j-1.6.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=ehcache-1.1.jar	-DartifactId=ehcache-1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=file-uploader-5.1-SNAPSHOT.jar	-DartifactId=file-uploader-5.1-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=hamcrest-all-1.3.jar	-DartifactId=hamcrest-all-1.3
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=hamcrest-core-1.1.jar	-DartifactId=hamcrest-core-1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=hamcrest-library-1.1.jar	-DartifactId=hamcrest-library-1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=hibernate-3.2.6.jar	-DartifactId=hibernate-3.2.6
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=httpclient-4.2.5.jar	-DartifactId=httpclient-4.2.5
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=httpcore-4.2.4.jar	-DartifactId=httpcore-4.2.4
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=iText-2.1.7.jar	-DartifactId=iText-2.1.7
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jackson-annotations-2.8.0.jar	-DartifactId=jackson-annotations-2.8.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jackson-core-2.8.1.jar	-DartifactId=jackson-core-2.8.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jackson-databind-2.8.1.jar	-DartifactId=jackson-databind-2.8.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jakarta-oro.jar	-DartifactId=jakarta-oro
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jasperreports-3.7.2.jar	-DartifactId=jasperreports-3.7.2
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jasperreports-applet-3.7.2.jar	-DartifactId=jasperreports-applet-3.7.2
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jcommon-1.0.16.jar	-DartifactId=jcommon-1.0.16
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jdbc-se2.0.jar	-DartifactId=jdbc-se2.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jdom-1.0.jar	-DartifactId=jdom-1.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jdt-compiler-3.1.1.jar	-DartifactId=jdt-compiler-3.1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jfreechart-1.0.13.jar	-DartifactId=jfreechart-1.0.13
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jmock-2.5.1.jar	-DartifactId=jmock-2.5.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jmock-junit4-2.5.1.jar	-DartifactId=jmock-junit4-2.5.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=joda-time-2.1.jar	-DartifactId=joda-time-2.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=json_simple-1.1.jar	-DartifactId=json_simple-1.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jsp-api.jar	-DartifactId=jsp-api
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jta.jar	-DartifactId=jta
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=jta1.0.1.jar	-DartifactId=jta1.0.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=log4j-1.2.15.jar	-DartifactId=log4j-1.2.15
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=mail-1.4.1.jar	-DartifactId=mail-1.4.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=mail-appender-0.2-SNAPSHOT.jar	-DartifactId=mail-appender-0.2-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=mchange-commons-java-0.2.3.4.jar	-DartifactId=mchange-commons-java-0.2.3.4
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=ojdbc14.jar	-DartifactId=ojdbc14
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=opencsv-2.0.jar	-DartifactId=opencsv-2.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=persistence-api-1.0.2.jar	-DartifactId=persistence-api-1.0.2
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=postgresql-9.1-901.jdbc4.jar	-DartifactId=postgresql-9.1-901.jdbc4
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=quartz-2.2.0.jar	-DartifactId=quartz-2.2.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=resolver.jar	-DartifactId=resolver
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=rome-1.0.jar	-DartifactId=rome-1.0
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=serializer.jar	-DartifactId=serializer
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=servlet-api.jar	-DartifactId=servlet-api
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=slf4j-api-1.6.1.jar	-DartifactId=slf4j-api-1.6.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=slf4j-simple-1.6.1.jar	-DartifactId=slf4j-simple-1.6.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=standard.jar	-DartifactId=standard
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=struts.jar	-DartifactId=struts
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=struts2-core-2.0.9.jar	-DartifactId=struts2-core-2.0.9
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=struts2-spring-plugin-2.0.6.jar	-DartifactId=struts2-spring-plugin-2.0.6
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=web-clients-0.87-SNAPSHOT.jar	-DartifactId=web-clients-0.87-SNAPSHOT
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=xercesImpl.jar	-DartifactId=xercesImpl
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=xml-apis.jar	-DartifactId=xml-apis
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=xmlpull-1.1.3.1.jar	-DartifactId=xmlpull-1.1.3.1
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=xpp3_min-1.1.4c.jar	-DartifactId=xpp3_min-1.1.4c
mvn install:install-file -Dpackaging=jar -DgroupId=org.bahmni.lab -Dversion=1.0.0 -Dfile=xstream-1.4.3.jar	-DartifactId=xstream-1.4.3